version: "3.4"

services:
  app:
    build: ./
    ports:
      - "3050:3000"
  database:
      image: "postgres"
      volumes:
        - "dstu_helper_volume/db:/var/lib/postgresql/data/"
  redis:
    image: redis
    volumes:
      - "dstu_helper_volume/db:/data"
