version: "3.4"

services:
  app:
    environment:
      - VK_BOT_TOKEN
      - VK_BOT_ID
      - TG_BOT_TOKEN
      - DATABASE_HOST
      - DATABASE_USER
      - DATABASE_PASSWORD
      - DATABASE_NAME
      - REDIS_HOST
      - REDIS_PORT
      - TZ
      - ENV
    image: "registry.mtdl.ru/dstu_helper_app:1.1.0r1"
    ports:
      - "3050:3000"

  database:
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
      TZ: ${TZ}
    image: "postgres"
    volumes:
      - "uni_helper_bot_db:/var/lib/postgresql/data/"
    ports:
      - "13060:5432"

  redis:
    image: redis
    environment:
      - REDIS_HOST
      - REDIS_PORT
      - TZ
    volumes:
      - "uni_helper_bot_redis:/data"

volumes:
  uni_helper_bot_db:
    external: true
  uni_helper_bot_redis:
    external: true
