version: "3.4"

services:
  app:
    build: ./
    ports:
      - "3050:3000"
  database:
      image: "postgres"
      volumes:
        - "${PROJECT_DIR}/db:/var/lib/postgresql/data/"
  redis:
    image: redis
