version: "3.4"

services:
  app:
    environment:
      - BOT_TOKEN
      - TG_BOT_TOKEN
      - GROUP_ID
      - CONFIRMATION
      - DATABASE_URL
      - REDIS_HOST
      - REDIS_PORT
      - CHUNK_SIZE
      - SYSTEM_NOTIFICATION_TG_USER
      - FLAVOUR
      - TZ
    image: "registry.mtdl.ru/dstu_helper_app:1.0.6"
    ports:
      - "3050:3000"

  database:
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - TZ
    image: "postgres"
    volumes:
      - "dstu_helper_bot_db:/var/lib/postgresql/data/"
    ports:
      - "13050:3000"

  redis:
    image: redis
    environment:
      - REDIS_HOST
      - REDIS_PORT
      - TZ
    volumes:
      - "dstu_helper_bot_redis:/data"

volumes:
  dstu_helper_bot_db:
    external: true
  dstu_helper_bot_redis:
    external: true
