export enum TeacherDegree {
  ASSISTANT = 'ASSISTANT',
  DEAN = 'DEAN',
  DOCENT = 'DOCENT',
  DEPARTMENT_CHAIRMAN = 'DEPARTMENT_CHAIRMAN',
  TEACHER = 'TEACHER',
  PROFESSOR = 'PROFESSOR',
  SENIOR_TEACHER = 'SENIOR_TEACHER',
  NON_TYPE = 'NON_TYPE',
}
