export enum UserStage {
  NOT_PRIVATE_STARTED = 'NOT_PRIVATE_STARTED',
  INITIAL = 'INITIAL',
  INPUT_LANGUAGE = 'INPUT_LANGUAGE',
  INPUT_GROUP = 'INPUT_GROUP',
  FILTER_LESSON = 'FILTER_LESSON',
  DONE = 'DONE',
}
