export enum InternalEvent {
  SETUP_PRIVATE_SUCCESS = 'SETUP_PRIVATE_SUCCESS',
  SYSTEM_NOTIFICATION = 'SYSTEM_NOTIFICATION',
  BROADCAST_BUMP_GROUP_COURSE_NOTIFICATION = 'BROADCAST_BUMP_GROUP_COURSE_NOTIFICATION',
}
