name: ci

on:
  push:
    branches:
      - 'master'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag dstu_helper_app:latest
    - name: Login in private registry
      run: docker login https://registry.mtdl.ru
    - name: Push Docker image
      run: docker push dstu_helper_app:latest

