name: ci

on:
  push:
    branches:
      - 'master'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag https://registry.mtdl.ru/dstu_helper_app:latest
    - name: Push Docker image
      run: docker push https://registry.mtdl.ru/dstu_helper_app:latest

