export enum LessonType {
  LECTURE = 'LECTURE',
  PRACTICAL = 'PRACTICAL',
  PHYSICAL_EDUCATION = 'PHYSICAL_EDUCATION',
  LABORATORY = 'LABORATORY',
  EXAMINATION = 'EXAMINATION',
  EXAM_WITHOUT_MARK = 'EXAM_WITHOUT_MARK',
}
